add SSO Login
rh-mad-workshop/mad-dev-guides-m5 pull request #3
Opened 2024-02-13 14:38 UTC by varodrig

Do not merge YET.

2024-02-13 15:14 UTC, danieloh30 commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Next, navigate to the console of the lab OpenShift cluster at link:https://console-openshift-console.%SUBDOMAIN%/topology/ns/globex-%USERID%?view=graph[console^,role=external,window=openshiftconsol
"Login with your username and password (`%USERID%/openshift`)" should be removed since you already logged in to the web console. Also, the sentence (Next...) doesn't make sense. You're already in the console!

2024-02-13 15:22 UTC, varodrig commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Next, navigate to the console of the lab OpenShift cluster at link:https://console-openshift-console.%SUBDOMAIN%/topology/ns/globex-%USERID%?view=graph[console^,role=external,window=openshiftconsol
resolved

2024-02-13 15:27 UTC, danieloh30 commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Next, navigate to the console of the lab OpenShift cluster at link:https://console-openshift-console.%SUBDOMAIN%/topology/ns/globex-%USERID%?view=graph[console^,role=external,window=openshiftconsol
Awesome. Thanks for the quick fix!!

2024-02-13 22:35 UTC, varodrig commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Next, navigate to the console of the lab OpenShift cluster at link:https://console-openshift-console.%SUBDOMAIN%/topology/ns/globex-%USERID%?view=graph[console^,role=external,window=openshiftconsol
fixed

2024-02-19 22:25 UTC, danieloh30 requested changes

2024-02-19 22:25 UTC, danieloh30 commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Expect to see something like this (rearrange the topology as you see fit):
See the comment in https://github.com/rh-mad-workshop/mad-dev-guides-m6/pull/10

2024-02-20 15:33 UTC, varodrig commented on documentation/modules/ROOT/pages/add-event-streaming.adoc
> +. Expect to see something like this (rearrange the topology as you see fit):
@danieloh30  here the url is redirecting to Navigate to the console of the lab OpenShift cluster at link:https://console-openshift-console.%SUBDOMAIN%/topology/ns/globex-%USERID%?view=graph[console^,role=external,window=openshiftconsole].  can you point out the issue here?

2024-02-28 14:26 UTC, merged